# Generated by Django 4.0.3 on 2022-03-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_createdoctors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
