# Generated by Django 4.0.3 on 2022-03-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField()),
                ('time_slot', models.TimeField()),
                ('message', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('IN PROGRESS', 'In Progress'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='IN PROGRESS', max_length=11)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
            options={
                'db_table': 'dl_appointments',
            },
        ),
    ]
